#!/bin/bash
set -e

cd "$(dirname "$0")/.."

if [[ "$1" == co* ]]; then
    echo "Running tests for coverage (pytest --cov=app)..."
    uv run pytest --cov=app
else
    echo "Running tests (pytest)..."
    uv run pytest "$@" -vv
fi
